/**
 * Seed packages/games/src/shared/i18n/country-names.ts from countries-enriched.json.
 *
 * - `en` column: taken from `name_en` (matches what in-game debug data currently uses).
 * - `sv` column: taken from `name` (already curated Swedish field in the enriched data).
 *
 * Run once (and again if countries-enriched.json gains new entries):
 *   npx tsx scripts/generate-country-names.ts
 *
 * Entries where `name === name_en` are listed at the end — these are either
 * legitimately the same in Swedish (e.g. Andorra, Canada) or untranslated and
 * worth a manual review in the committed file.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

interface EnrichedCountry {
    iso2: string
    name: string
    name_en: string
}

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = resolve(ROOT, 'public/countries-enriched.json')
const OUT = resolve(ROOT, 'src/shared/i18n/country-names.ts')

const countries: EnrichedCountry[] = JSON.parse(readFileSync(SRC, 'utf8'))
countries.sort((a, b) => a.iso2.localeCompare(b.iso2))

const en: Record<string, string> = {}
const sv: Record<string, string> = {}
const untranslated: string[] = []

for (const c of countries) {
    en[c.iso2] = c.name_en
    sv[c.iso2] = c.name
    if (c.name === c.name_en) untranslated.push(`${c.iso2} ${c.name_en}`)
}

function format(table: Record<string, string>): string {
    const lines = Object.entries(table).map(([iso2, name]) => `        ${iso2}: ${JSON.stringify(name)},`)
    return lines.join('\n')
}

const file = `// Auto-generated by scripts/generate-country-names.ts.
// Source: public/countries-enriched.json (en = name_en, sv = name).
// Manual edits are fine; re-running the generator will overwrite.
export const COUNTRY_NAMES: Record<string, Record<string, string>> = {
    en: {
${format(en)}
    },
    sv: {
${format(sv)}
    },
}
`

writeFileSync(OUT, file)
console.log(`Wrote ${countries.length} countries to ${OUT}`)
console.log(`Entries where sv === en (review these for missing translation): ${untranslated.length}`)
for (const line of untranslated) console.log('  ' + line)
